# Generated by Django 5.2.1 on 2025-05-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='valid_notification',
        ),
    ]
